### PR TITLE
Read file as binary

### PR DESCRIPTION
**Pull request by herrernst**
only convert text mimetypes to utf8 and apply replacing
also add default mimetype if mapping not found

### CODE REVIEW

**Comment by jzaefferer** [comment]
Diff looks good to me. Haven't tested it.

**Comment by shirish87** [comment]
@jzaefferer, in addition to binary and mp4 files, there have been requests for supporting streaming media (with range support, etc.) for [js controlling HTML5 audio/video](https://github.com/shirish87/browserstack-runner-media-sample). Browsers don't autoplay media without certain response headers in place. I thought it was best to offload serving non-HTML files to the [`send`](https://npmjs.com/package/send) module.

Committed the change to `master` in a hurry. Could you please review https://github.com/browserstack/browserstack-runner/commit/452e0d12880bfbf62f19f4a59e670caf8a0749db?
Thanks.

**Comment by jzaefferer** [comment]
Looks good to me.

**Comment by jzaefferer** [comment]
Replaced by 452e0d12880bfbf62f19f4a59e670caf8a0749db

**Pull request closed without merging**
