### PR TITLE
updated yargs version to 15.3.1

### PR DESCRIPTION
**Pull request by RohanImmanuel**

### CODE REVIEW

**Comment by RohanImmanuel** [comment]
This was raised to fix https://github.com/browserstack/browserstack-runner/issues/228

**Comment by romainmenke** [comment]
any news on when this might go through together with a new release?

**Comment by RohanImmanuel** [comment]
@romainmenke this is released with browserstack-runner v0.9.2

**Comment by romainmenke** [comment]
@RohanImmanuel thank you!
Security alert is resolved 👍

**Pull request merged**
